name: yet_another_json_isolate
description: Create isolates to parse JSON
version: 1.0.0
homepage: https://github.com/supabase-community/json-isolate-dart

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  async: ^2.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
