blank_issues_enabled: false
contact_links:
  - name: Open an Issue
    url: https://github.com/supabase-community/supabase-flutter/issues/new/choose
    about: We consolidate all Dart/ Flutter related issues on the supabase-flutter repo. 
